export enum WechatVirtualPaymentErrorCode {
  ACCESS_TOKEN_FAILED = 'WVP_ACCESS_TOKEN_FAILED',
  INVALID_ENCODING_AES_KEY = 'WVP_INVALID_ENCODING_AES_KEY',
  MESSAGE_APP_ID_MISMATCH = 'WVP_MESSAGE_APP_ID_MISMATCH',
  MESSAGE_DECRYPT_FAILED = 'WVP_MESSAGE_DECRYPT_FAILED',
  MESSAGE_FORMAT_INVALID = 'WVP_MESSAGE_FORMAT_INVALID',
  MESSAGE_PADDING_INVALID = 'WVP_MESSAGE_PADDING_INVALID',
  MESSAGE_SIGNATURE_INVALID = 'WVP_MESSAGE_SIGNATURE_INVALID',
  QUERY_FAILED = 'WVP_QUERY_FAILED',
  QUERY_ORDER_INVALID = 'WVP_QUERY_ORDER_INVALID',
  QUERY_REQUEST_FAILED = 'WVP_QUERY_REQUEST_FAILED',
  QUERY_RESPONSE_INVALID = 'WVP_QUERY_RESPONSE_INVALID',
}
