import { MigrationInterface, QueryRunner } from 'typeorm';

export class InitTables1786180634310 implements MigrationInterface {
  name = 'InitTables1786180634310';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
            CREATE TABLE "moto_assistant"."fuel_records" (
                "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                "moto_id" integer NOT NULL,
                "current_mileage" numeric(12, 1) NOT NULL,
                "refuel_date" TIMESTAMP WITH TIME ZONE NOT NULL,
                "refuel_amount" numeric(12, 2) NOT NULL,
                "unit_price" numeric(10, 4) NOT NULL,
                "fuel_count" numeric(12, 4) NOT NULL,
                "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
                "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
                CONSTRAINT "PK_9dbfb8fb6ec138c89ad8c043642" PRIMARY KEY ("id")
            )
        `);
    await queryRunner.query(`
            CREATE INDEX "idx_fuel_records_moto_date_id" ON "moto_assistant"."fuel_records" ("moto_id", "refuel_date", "id")
        `);
    await queryRunner.query(`
            CREATE TABLE "moto_assistant"."motos" (
                "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                "owner_id" integer NOT NULL,
                "moto_name" character varying(100) NOT NULL,
                "moto_buy_date" date NOT NULL,
                "moto_license_plate" character varying(50) NOT NULL,
                "moto_photo_url" character varying(1000) NOT NULL,
                "status" character varying(32) NOT NULL DEFAULT 'active',
                "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
                "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
                CONSTRAINT "PK_a9723c8df6e005cce29fe00df21" PRIMARY KEY ("id")
            )
        `);
    await queryRunner.query(`
            CREATE INDEX "idx_motos_owner_status_updated" ON "moto_assistant"."motos" ("owner_id", "status", "updated_at")
        `);
    await queryRunner.query(`
            CREATE TABLE "moto_assistant"."users" (
                "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                "open_id" character varying(64) NOT NULL,
                "nick_name" character varying(100) NOT NULL,
                "gender" character varying(16) NOT NULL,
                "language" character varying(16) NOT NULL,
                "city" character varying(100) NOT NULL,
                "province" character varying(100) NOT NULL,
                "country" character varying(100) NOT NULL,
                "avatar_url" character varying(1000) NOT NULL,
                "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
                "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
                CONSTRAINT "UQ_04ea25bc0c6f11376c0ed56a046" UNIQUE ("open_id"),
                CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id")
            )
        `);
    await queryRunner.query(`
            CREATE TABLE "moto_assistant"."auth_sessions" (
                "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                "user_id" integer NOT NULL,
                "token_hash" character varying(64) NOT NULL,
                "absolute_expires_at" TIMESTAMP WITH TIME ZONE NOT NULL,
                "idle_expires_at" TIMESTAMP WITH TIME ZONE NOT NULL,
                "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
                "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
                CONSTRAINT "UQ_fc7c8b01bebb6839399c494d68a" UNIQUE ("token_hash"),
                CONSTRAINT "PK_641507381f32580e8479efc36cd" PRIMARY KEY ("id")
            )
        `);
    await queryRunner.query(`
            CREATE INDEX "idx_auth_sessions_idle_expires" ON "moto_assistant"."auth_sessions" ("idle_expires_at")
        `);
    await queryRunner.query(`
            CREATE INDEX "idx_auth_sessions_absolute_expires" ON "moto_assistant"."auth_sessions" ("absolute_expires_at")
        `);
    await queryRunner.query(`
            CREATE INDEX "idx_auth_sessions_user" ON "moto_assistant"."auth_sessions" ("user_id")
        `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
            DROP INDEX "moto_assistant"."idx_auth_sessions_user"
        `);
    await queryRunner.query(`
            DROP INDEX "moto_assistant"."idx_auth_sessions_absolute_expires"
        `);
    await queryRunner.query(`
            DROP INDEX "moto_assistant"."idx_auth_sessions_idle_expires"
        `);
    await queryRunner.query(`
            DROP TABLE "moto_assistant"."auth_sessions"
        `);
    await queryRunner.query(`
            DROP TABLE "moto_assistant"."users"
        `);
    await queryRunner.query(`
            DROP INDEX "moto_assistant"."idx_motos_owner_status_updated"
        `);
    await queryRunner.query(`
            DROP TABLE "moto_assistant"."motos"
        `);
    await queryRunner.query(`
            DROP INDEX "moto_assistant"."idx_fuel_records_moto_date_id"
        `);
    await queryRunner.query(`
            DROP TABLE "moto_assistant"."fuel_records"
        `);
  }
}
