import { MigrationInterface, QueryRunner } from 'typeorm';

export class AddTipOrders1788406303959 implements MigrationInterface {
  name = 'AddTipOrders1788406303959';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
            CREATE TABLE "moto_assistant"."tip_orders" (
                "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                "out_trade_no" character varying(32) NOT NULL,
                "client_request_id" character varying(64) NOT NULL,
                "user_id" integer NOT NULL,
                "payer_open_id" character varying(64) NOT NULL,
                "product_id" character varying(64) NOT NULL,
                "unit_price" integer NOT NULL,
                "quantity" integer NOT NULL,
                "total_amount" integer NOT NULL,
                "environment" smallint NOT NULL,
                "status" character varying(32) NOT NULL DEFAULT 'pending',
                "wx_order_id" character varying(128),
                "paid_at" TIMESTAMP WITH TIME ZONE,
                "refunded_at" TIMESTAMP WITH TIME ZONE,
                "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
                "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
                CONSTRAINT "UQ_797feb2804839796f246605e942" UNIQUE ("out_trade_no"),
                CONSTRAINT "UQ_8cbb5c44dc0ded1079c4998bf6e" UNIQUE ("client_request_id"),
                CONSTRAINT "UQ_470930d14ac903b701af2d08809" UNIQUE ("wx_order_id"),
                CONSTRAINT "PK_405f843d28cc69afd72b4701928" PRIMARY KEY ("id")
            )
        `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
            DROP TABLE "moto_assistant"."tip_orders"
        `);
  }
}
